baseurl = "/"
languageCode = "en-us"
title = "Train Effective Blog"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Train like a pro."
  cover = "images/cover.jpg"
  author = "Nick Humphries"
  authorlocation = "London, England"
  authorwebsite = "https://traineffective.com"
  bio= "Challenging the status quo everyday. Australian, but played for clubs in Hungary, The Netherlands & Switzerland. Spreading the vision that you can become whatever you put your mind to as founder of TrainEffective.com."
  logo = "images/logo.svg"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  # githubName = "vjeantet"
  twitterName = "TrainEffective"
  facebookName="TrainEffective"
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "TrainEffective"
    facebookName="TrainEffective"
